### ISSUE TITLE
Dancer2 v0.204004, Template::Toolkit   (not fixed)

### ISSUE THREAD

**Issue by h707** [PerlDancer/Dancer2#1309]
Dancer2 v0.204004, Template v2.26, Ubuntu 16.04.
[ BUG FIXES ]
    * GH #1307: Fix breakage of Template::Toolkit, caused by
previous release. (Peter SysPete Mottram)

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      START_TAG: '[%'
      END_TAG:  '%]'
      COMPILE_DIR: '/tmp/ttc'

`<!DOCTYPEhml><hmll="u"><hd><mhp-quiv="C-yp"="x/hml;h=[ih]"/>`

**Comment by SysPete** [comment]
@h707 one of things that was reverted was the use of upper case configuration directives. Could you please retry with config more like this:
```
template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '[%'
      end_tag:   '%]'
```

**Comment by h707** [comment]
Error corrected in such a configuration:
```
engines:
  template:
    template_toolkit:
      start_tag: '[%'
      end_tag:  '%]'
      COMPILE_DIR: '/tmp/ttc'
```
