### ISSUE TITLE
Not working custom login template with Template toolkit.

### ISSUE THREAD

**Issue by lufthansa77** [PerlDancer/Dancer2#1313]
Hello,
  when i use module Dancer2::Plugin::Auth::Extensible and i want load  
 own login template it is not working. And i get error:

```
 [test1:26266] debug @2017-02-06 20:02:34> app has no login template defined in /home/perltest2/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/Dancer2/Core/Route.pm l. 140
```
 
When template_toolkit is disabled, custom template is loaded correctly.

```
  Dancer2-0.204004
  perl v5.18.4
  Dancer2-Plugin-Auth-Extensible-0.703
```

config.yml 

```
appname: "test1"
layout: "main"

charset: "UTF-8"

logger: 'console'
log: 'debug' 
traces: 1

template: template_toolkit

engines:
  session:
    YAML:
      #is_secure: 1
      is_http_only: 1
      session_dir: "/tmp/dancer-sessions"

  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'
      show_private_variables: true

plugins:
    Auth::Extensible:
        login_without_redirect: 1
        login_template: login2
		        realms:
            config:
                provider: Config
                users:
                    - user: dave
                      pass: dave
                      roles:
                        - Developer
                        - Manager
                        - BeerDrinker

```

Many thanks for any help.
 Regards Dan
