### ISSUE TITLE
Configuration ignored?

### ISSUE THREAD

**Issue by dverdin** [PerlDancer/Dancer2#1537]
Dear all,
 I'm trying to use a config.yml file but I must be missing something...

I bootstraped the app and now I have the following:

```
myapp/bin/app.psgi
myapp/src (contains all the code)
myapp/environments (contains development.yml and production.yml)
```

When I change parameters in either an environement file or another, it does not seem to have any effect when running:

`plackup -E development bin/app.psgi`

For example, it ignores the port and server parameters. It also ignores startup_info.
And more than all, it ignores the configuration I made for the database access.

Here is on of the config file:

```
logger: "console"

log: "core"

warnings: 1

show_errors: 1

startup_info: 1

port: 1234

server: 1.1.1.1

plugins:
  DBIC:
    gnothi:
      dsn: "dbi:SQLite:dbname=t/db/app.sqlite"
      user: my-user
      password: my-password
      schema_class: My::Schema
      options:
        mysql_enable_utf8: 1
```
Any clue about what I am missing? I am quite despaired...
Thanks!
David
