### ISSUE TITLE
Issues with configuration

### ISSUE THREAD

**Issue by JJ** [PerlDancer/Dancer2#1584]
As indicated in #1583, there's some ambiguity on where the `config.yml` file would go. But additionally, there're a few issues:

* Some settings simply do not seem to work. `port` is simply ignored, for instance. Apparently, `content_type` too.
* There seems to be some dependence on where the `logger` directive is placed, which, a YAML file being declarative, probably should not.
* When using a configuration file, additional settings seem to be ignored. 

```yaml
port: 31415
content_type: "application/json"
engines:
  logger:
    File:
      log_level: core
      file_name: "hitos.log"
logger: "File"
```
followed by `set log_dir => '/tmp'` is simply ignored.
