### ISSUE TITLE
Dancer2::Session::YAML not working

### ISSUE THREAD

**Issue by davidanrod** [PerlDancer/Dancer2#661]
Followed this example:

```
session: "YAML"
engines:
  session:
    YAML:
      session_dir: "/tmp/dancer-sessions"
```

Even using default setting which is "sessions", produce no result. none file is created inside directory
